name: AIDictionary
options:
  bundleIdPrefix: site.waterlee.aidic
  deploymentTarget:
    macOS: "13.0"
  createIntermediateGroups: true
  xcodeVersion: "14.0"
targets:
  AIDictionary:
    type: application
    platform: macOS
    sources: 
      - path: AIDictionary
        excludes:
          - "**/*.md"
          - "**/Preview Content/**"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: site.waterlee.aidic.AIDictionary
        INFOPLIST_FILE: AIDictionary/Info.plist
        MACOSX_DEPLOYMENT_TARGET: "13.0"
        CODE_SIGN_ENTITLEMENTS: AIDictionary/AIDictionary.entitlements
        CODE_SIGN_IDENTITY: "Mac Developer"
        DEVELOPMENT_TEAM: "6RT3UH94M6"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        COMBINE_HIDPI_IMAGES: YES
        SDKROOT: macosx
        SWIFT_VERSION: "5.0"
        SWIFT_OPTIMIZATION_LEVEL: "-Onone"
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
        CLANG_ENABLE_MODULES: YES
        CLANG_ENABLE_OBJC_ARC: YES
        CLANG_ENABLE_OBJC_WEAK: YES
        CLANG_WARN_BOOL_CONVERSION: YES
        CLANG_WARN_CONSTANT_CONVERSION: YES
        CLANG_WARN_DOCUMENTATION_COMMENTS: YES
        CLANG_WARN_EMPTY_BODY: YES
        CLANG_WARN_ENUM_CONVERSION: YES
        CLANG_WARN_INT_CONVERSION: YES
        CLANG_WARN_UNREACHABLE_CODE: YES
        GCC_WARN_64_TO_32_BIT_CONVERSION: YES
        GCC_WARN_ABOUT_RETURN_TYPE: YES_ERROR
        GCC_WARN_UNDECLARED_SELECTOR: YES
        GCC_WARN_UNINITIALIZED_AUTOS: YES_AGGRESSIVE
        GCC_WARN_UNUSED_FUNCTION: YES
        GCC_WARN_UNUSED_VARIABLE: YES
    info:
      path: AIDictionary/Info.plist
    entitlements:
      path: AIDictionary/AIDictionary.entitlements
    dependencies: []
    scheme:
      testTargets:
        - AIDictionaryTests

  AIDictionaryTests:
    type: bundle.unit-test
    platform: macOS
    sources: 
      - path: AIDictionaryTests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: site.waterlee.aidic.AIDictionaryTests
        INFOPLIST_FILE: AIDictionaryTests/Info.plist
        MACOSX_DEPLOYMENT_TARGET: "13.0"
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/AIDictionary.app/Contents/MacOS/AIDictionary"
    info:
      path: AIDictionaryTests/Info.plist
    dependencies:
      - target: AIDictionary 